apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - role.yaml
  - rolebinding.yaml
  - postgresql-service.yaml
  - postgresql-deployment.yaml
  - postgresql-pvc.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
