apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: devops-control-plane
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ocp-rbd-rook
  resources:
    requests:
      storage: 5Gi
