apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-control-plane-oauth-proxy
  namespace: devops-control-plane
  labels:
    app.kubernetes.io/name: devops-control-plane
    app.kubernetes.io/component: oauth-proxy
