apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../deployment.yaml
  - ../../service.yaml
  - ../../route.yaml
  - oauth-proxy-serviceaccount.yaml
  - oauth-proxy-tekton-rolebinding.yaml

patches:
  - path: patch-deployment-oauth-proxy.yaml
  - path: patch-service-oauth-proxy.yaml
  - path: patch-route-oauth-proxy.yaml
